cache: &global_cache
  key: ${CI_PROJECT_ID}-php
  paths:
    - php/test/vendor/
    - php/test/vendor/
    - /tmp/composercache/
stages:
  - build

php7.3:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - wget https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
    - tar -C ./usr/local/bin -xzvf docker-squash-linux-amd64-v0.2.0.tar.gz
    - chmod +x /usr/local/bin/docker-squash
    - export DOCKER_PREFIX=nlzet/php:7.3
    - export FROM_IMAGE=php:7.3-fpm
    - export PHP_EXTENSIONS="amqp bcmath bz2 exif gd gettext gmp igbinary imagick intl mcrypt mongodb mysqli pdo_mysql pdo_pgsql redis sockets soap xdebug xmlrpc xsl zip"
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
#    - ./php/build.sh
#    - docker run -v /tmp/composercache/:/home/www/.composer/cache/ -v $(pwd)/php/test/:/var/www -i ${DOCKER_PREFIX}-cli composer install
#    - ./php/test.sh
    - ./php/squash.sh
#    - ./php/push.sh
  services:
    - name: docker:dind
      alias: docker

php7.4:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - wget https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
    - tar -C ./usr/local/bin -xzvf docker-squash-linux-amd64-v0.2.0.tar.gz
    - chmod +x /usr/local/bin/docker-squash
    - export DOCKER_PREFIX=nlzet/php:7.4
    - export FROM_IMAGE=php:7.4-fpm
    - export PHP_EXTENSIONS="amqp bcmath bz2 exif gd gettext gmp igbinary imagick intl mcrypt mongodb mysqli pdo_mysql pdo_pgsql redis sockets soap xdebug xmlrpc xsl zip"
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
#    - ./php/build.sh
#    - docker run -v /tmp/composercache/:/home/www/.composer/cache/ -v $(pwd)/php/test/:/var/www -i ${DOCKER_PREFIX}-cli composer install
#    - ./php/test.sh
    - ./php/squash.sh
#    - ./php/push.sh
  services:
    - name: docker:dind
      alias: docker

php8.0:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - wget https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
    - tar -C ./usr/local/bin -xzvf docker-squash-linux-amd64-v0.2.0.tar.gz
    - chmod +x /usr/local/bin/docker-squash
    - export DOCKER_PREFIX=nlzet/php:8.0
    - export FROM_IMAGE=php:8.0.0RC5-fpm
    - export PHP_EXTENSIONS="gd bcmath bz2 exif gd gettext gmp igbinary intl mysqli pdo_mysql pdo_pgsql redis sockets soap xdebug xsl zip"
    # currently unsupported php8 extensions (https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions)
    # amqp imagick mcrypt mongodb xmlrpc
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
#    - ./php/build.sh
#    - docker run -v /tmp/composercache/:/home/www/.composer/cache/ -v $(pwd)/php/test/:/var/www -i ${DOCKER_PREFIX}-cli composer install
#    - ./php/test.sh
    - ./php/squash.sh
#    - ./php/push.sh
  services:
    - name: docker:dind
      alias: docker
