cache: &global_cache
  key: ${CI_PROJECT_ID}-php
  paths:
    - php/test/vendor/
    - php/test/vendor/
    - /tmp/composercache/
stages:
  - build

php73:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - export DOCKER_PREFIX=nlzet/php:7.3
    - export PHP_FROM=php:7.3-fpm
    - export PHP_EXTENSIONS="apcu apcu_bc amqp bcmath bz2 exif gd gettext gmp igbinary imagick intl mcrypt mongodb mysqli pdo_mysql pdo_pgsql redis soap ssh2 xdebug xmlrpc xsl zip"
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - ./php/build.sh
    - docker run -v /tmp/composercache/:/home/www/.composer/cache/ -v $(pwd)/php/test/:/var/www -i ${DOCKER_PREFIX}-cli composer install
    - ./php/test.sh
    - ./php/push.sh
  services:
    - name: docker:dind
      alias: docker

php74:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - export DOCKER_PREFIX=nlzet/php:7.4
    - export PHP_FROM=php:7.4-fpm
    - export PHP_EXTENSIONS="apcu apcu_bc amqp bcmath bz2 exif gd gettext gmp igbinary imagick intl mcrypt mongodb mysqli pdo_mysql pdo_pgsql redis soap ssh2 xdebug xmlrpc xsl zip"
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - ./php/build.sh
    - docker run -v /tmp/composercache/:/home/www/.composer/cache/ -v $(pwd)/php/test/:/var/www -i ${DOCKER_PREFIX}-cli composer install
    - ./php/test.sh
    - ./php/push.sh
  services:
    - name: docker:dind
      alias: docker

php80:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - export DOCKER_PREFIX=nlzet/php:8.0
    - export PHP_FROM=php:8.0.0RC5-fpm
    - export PHP_EXTENSIONS="gd"
    # tmp disabled
    # apcu bcmath bz2 exif gd gettext gmp igbinary intl mysqli pdo_mysql pdo_pgsql redis soap xdebug xsl zip
    # unsupported php8 extensions
    # amqp apcu_bc imagick mcrypt mongodb ssh2 xmlrpc
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - ./php/build.sh
#    - docker run -v /tmp/composercache/:/home/www/.composer/cache/ -v $(pwd)/php/test/:/var/www -i ${DOCKER_PREFIX}-cli composer install
#    - ./php/test.sh
    - ./php/push.sh
  services:
    - name: docker:dind
      alias: docker
