stages:
  - build

php73:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - docker build --build-arg FROM_IMAGE=php:7.3-cli --target cli-stage -t nlzet/php73:cli php/ --pull
    - docker push nlzet/php73:cli
    - docker build --build-arg FROM_IMAGE=php:7.3-fpm --target fpm-stage -t nlzet/php73:fpm php/
    - docker push nlzet/php73:fpm
    - docker build --build-arg FROM_IMAGE=php:7.3-fpm --target ci-stage -t nlzet/php73:ci --cache-from=nlzet/php73:fpm php/
    - docker push nlzet/php73:ci
  services:
    - name: docker:dind
      alias: docker

php74:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - docker build --build-arg FROM_IMAGE=php:7.4-cli --target cli-stage -t nlzet/php74:cli php/ --pull
    - docker push nlzet/php74:cli
    - docker build --build-arg FROM_IMAGE=php:7.4-fpm --target fpm-stage -t nlzet/php74:fpm php/
    - docker push nlzet/php74:fpm
    - docker build --build-arg FROM_IMAGE=php:7.4-fpm --target ci-stage -t nlzet/php74:ci --cache-from=nlzet/php74:fpm php/
    - docker push nlzet/php74:ci
  services:
    - name: docker:dind
      alias: docker
