cache: &global_cache
  key: ${CI_PROJECT_ID}-build-php
  paths:
    - php/test/vendor/
    - /tmp/composercache/
stages:
  - build

php8.1:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - apk update && apk add tar sudo
    - export PHP_VERSION=8.1
    - export NODE_MAJOR=16
    - export DOCKER_PREFIX=nlzet/php
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - ./run.sh build cli stage1 "--no-cache"
    - ./run.sh build fpm stage2
    - ./run.sh build ci stage3
    - docker run -w /var/www/php/test/ -v /tmp/composercache/:/home/www/.composer/cache/ -v $(pwd)/:/var/www -i ${DOCKER_PREFIX}:${PHP_VERSION}-cli composer update -W
    - ./run.sh testxdebug
    - ./run.sh push cli
    - ./run.sh push fpm
    - ./run.sh push ci
  artifacts:
    paths:
      - php/test/data/out_*
    expire_in: 7 days
    when: always
  services:
    - name: docker:dind
      alias: docker

php8.2:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - apk update && apk add tar sudo
    - export PHP_VERSION=8.2
    - export NODE_MAJOR=18
    - export DOCKER_PREFIX=nlzet/php
    # skip mcrypt on php 8.2
    - export PHP_EXTENSIONS="@composer amqp bcmath bz2 exif ffi gd gettext gmp igbinary imagick intl mysqli pcntl pdo_mysql pdo_pgsql redis sockets soap xdebug xmlrpc xsl zip"
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - ./run.sh build cli stage1 "--no-cache"
    - ./run.sh build fpm stage2
    - ./run.sh build ci stage3
    - docker run -w /var/www/php/test/ -v /tmp/composercache/:/home/www/.composer/cache/ -v $(pwd)/:/var/www -i ${DOCKER_PREFIX}:${PHP_VERSION}-cli composer update -W
    - ./run.sh testxdebug
    - ./run.sh push cli
    - ./run.sh push fpm
    - ./run.sh push ci
  artifacts:
    paths:
      - php/test/data/out_*
    expire_in: 7 days
    when: always
  services:
    - name: docker:dind
      alias: docker

php8.3:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - apk update && apk add tar sudo
    - export PHP_VERSION=8.3
    - export NODE_MAJOR=20
    - export DOCKER_PREFIX=nlzet/php
    # skip imagick on php 8.3
    - export PHP_EXTENSIONS="@composer amqp bcmath bz2 exif ffi gd gettext gmp igbinary intl mcrypt mysqli pcntl pdo_mysql pdo_pgsql redis sockets soap xdebug xmlrpc xsl zip"
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - ./run.sh build cli stage1 "--no-cache"
    - ./run.sh build fpm stage2
    - ./run.sh build ci stage3
    - docker run -w /var/www/php/test/ -v /tmp/composercache/:/home/www/.composer/cache/ -v $(pwd)/:/var/www -i ${DOCKER_PREFIX}:${PHP_VERSION}-cli composer update -W
    - ./run.sh testxdebug
    - ./run.sh push cli
    - ./run.sh push fpm
    - ./run.sh push ci
  artifacts:
    paths:
      - php/test/data/out_*
    expire_in: 7 days
    when: always
  services:
    - name: docker:dind
      alias: docker
