stages:
  - build

php73:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - export DOCKER_PREFIX=nlzet/php:7.3
    - export PHP_FROM=php:7.3-fpm
    - export PHP_EXTENSIONS="gd xdebug intl xmlrpc xsl gettext gmp bcmath zip bz2 soap mysqli pdo_mysql pdo_pgsql mongodb amqp imagick igbinary ssh2 exif mcrypt redis"
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - ./php/build.sh
  services:
    - name: docker:dind
      alias: docker

php74:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - export DOCKER_PREFIX=nlzet/php:7.4
    - export PHP_FROM=php:7.4-fpm
    - export PHP_EXTENSIONS="gd xdebug intl xmlrpc xsl gettext gmp bcmath zip bz2 soap mysqli pdo_mysql pdo_pgsql mongodb amqp imagick igbinary ssh2 exif mcrypt redis"
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - ./php/build.sh

  services:
    - name: docker:dind
      alias: docker

php80:
  tags: ["docker"]
  stage: build
  image: docker
  script:
    - export DOCKER_PREFIX=nlzet/php:8.0
    - export PHP_FROM=php:8.0.0RC5-fpm
    - export PHP_EXTENSIONS="gd xdebug intl xmlrpc xsl gettext gmp bcmath zip bz2 soap mysqli pdo_mysql pdo_pgsql mongodb amqp imagick igbinary ssh2 exif mcrypt redis"
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - ./php/build.sh
  services:
    - name: docker:dind
      alias: docker
